Death_star/Death_star/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index_redirect

urlpatterns = [
    path('root_of_evil/', admin.site.urls),
    path('', index_redirect, name='index'),
    path('core/', include('core.urls', namespace='core')),
]

Death_star/core/urls.py
from django.urls import path, include
from core.views import IndexView, CreateRecruitView, Questions, CongratulationsView, SithsListView, RecruitsListView, \
    SithsShortcutListView, RecruitDetailView

app_name = 'core'

urlpatterns = [
    path('main/', IndexView.as_view(), name='main'),
    path('create/rec/', CreateRecruitView.as_view(), name='create_rec'),
    path('create/rec/questions/', Questions.as_view(), name='recruit_questions'),
    path('create/rec/congratulations/', CongratulationsView.as_view(), name='congratulations'),
    path('choose/sith/', SithsListView.as_view(), name='all_siths'),
    path('choose/sith/recruit/<int:pk>/', RecruitDetailView.as_view(), name='rec_detail'),
    path('choose/sith/shortcut', SithsShortcutListView.as_view(), name='all_siths_shortcut'),
    path('choose/sith/recruit', RecruitsListView.as_view(), name='all_recruits'),
]

Death_star/core/models.py
from django.db import models


class Planet(models.Model):
    name = models.CharField(max_length=100, verbose_name='Зловещее название')

    def __str__(self):
        return self.name


class Recruit(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя')
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE, verbose_name='Родная планета')
    age = models.IntegerField(verbose_name='Возраст')
    email = models.EmailField(verbose_name='Почтовый ящик', max_length=254)

    def is_complete_test(self):
        if QuestionChoice.objects.filter(voted=self).distinct():
            return True
        else:
            return False

    def is_shadow_hand(self):
        siths = Sith.objects.all()
        for sith in siths:
            try:
                sith.padavans.get(id=self.id)
                return True
            except self.DoesNotExist:
                continue
        return False

    def __str__(self):
        return 'Новичок %s с %s' % (self.name, self.planet.name)


class Sith(models.Model):
    name = models.CharField(max_length=50, verbose_name='Ужасающее имя')
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE, verbose_name='Родная планета')
    padavans = models.ManyToManyField(Recruit, blank=True, verbose_name='Будущие ситхи')

    def __str__(self):
        return 'Владыка %s c %s' % (self.name, self.planet.name)


class ShadowHandQuestion(models.Model):
    description = models.TextField(max_length=254, verbose_name='Описание вопроса')

    def __str__(self):
        return self.description[0:50]


class QuestionChoice(models.Model):
    task = models.ForeignKey(ShadowHandQuestion, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=250, verbose_name='Вариант ответа')
    voted = models.ForeignKey(Recruit, on_delete=models.CASCADE, verbose_name='Голосовавший', blank=True)

    def __str__(self):
        return 'Ответ на вопрос %d от %s' % (self.task.id, self.voted.name)

Death_star/core/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.shortcuts import render
from django.core.mail import EmailMessage

from core.models import Recruit, ShadowHandQuestion, QuestionChoice, Sith


def index_redirect(request):
    return HttpResponseRedirect(reverse('core:main'))


class CongratulationsView(generic.TemplateView):
    template_name = 'core/congratulations.html'


class IndexView(generic.TemplateView):
    template_name = 'core/index.html'


class CreateRecruitView(generic.CreateView):
    template_name = 'core/create_recruit.html'
    model = Recruit
    fields = '__all__'

    def form_valid(self, form):
        recruit = form.save()
        self.request.session['recruit_id'] = recruit.id
        return HttpResponseRedirect(reverse('core:recruit_questions'))


class Questions(generic.ListView):
    template_name = 'core/questions.html'
    context_object_name = 'question_list'

    def get_queryset(self):
        return ShadowHandQuestion.objects.all()

    def post(self, request):
        questions = ShadowHandQuestion.objects.all()
        rec_id = self.request.session['recruit_id']
        recruit = Recruit.objects.get(id=rec_id)
        for question in questions:
            QuestionChoice.objects.create(task=question,
                                          choice_text=self.request.POST['answer-%d' % question.id],
                                          voted=recruit)
        return HttpResponseRedirect(reverse('core:congratulations'))


class SithsListView(generic.ListView):
    template_name = 'core/siths_list.html'
    context_object_name = 'siths_list'

    def get_queryset(self):
        return Sith.objects.all()

    def post(self, request):
        self.request.session['sith_name'] = self.request.POST['sith-id']
        return HttpResponseRedirect(reverse('core:all_recruits'))


class SithsShortcutListView(generic.ListView):
    template_name = 'core/siths_list_shortcut.html'
    context_object_name = 'siths_list'

    def get_queryset(self):
        return Sith.objects.all()


class RecruitDetailView(generic.DetailView):
    template_name = 'core/recruit_detail.html'
    model = Recruit
    context_object_name = 'recruit'

    def get_queryset(self):
        return Recruit.objects.filter(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recruit_answers'] = QuestionChoice.objects.filter(voted__in=self.get_queryset())
        return context


class RecruitsListView(generic.ListView):
    template_name = 'core/recruits_list.html'
    context_object_name = 'rec_list'

    def get_queryset(self):
        return Recruit.objects.all()

    def post(self, request):
        choices = request.POST.getlist('recruit-id')
        sith_name = request.session['sith_name']
        sith = Sith.objects.get(name=sith_name)
        if (len(choices) + sith.padavans.count()) > 3:
            return render(request, 'core/notify.html',
                          {'error': 'К сожалению не можете иметь больше 3х падаванов, господин',
                           'message': 'Что-то пошло не так'})
        else:
            for choice in choices:
                recruit = Recruit.objects.get(id=choice)
                sith.padavans.add(recruit)
                sith.save()
                email = self.generate_email(sith, recruit)
                email.send()
            return render(request, 'core/notify.html',
                          {'message': 'Успех! Рекрут оповещен и зачислен в ряды Рук Смерти!'})

    def generate_email(self, sith, recruit):
        email_message = EmailMessage('Поздравляем, теперь у тебя есть сенсей',
                                     'Лорд %s согласился взять тебя в ученики' % sith.name,
                                     to=[recruit.email])
        return email_message

Death_star/templates/core/congratulations.html
{% extends 'core/wrapper.html' %}

{% block title %}Поздравляем{% endblock %}

{% block content %}
    <h3>Поздравляем!</h3>
    <p>Вот-вот ты станешь рукой тьмы (но это не точно)</p>
    <p>Если же вдруг тебе повезет, то ты получишь оповещением по почте</p>
    <p>(буду рад, если на первой же миссии тебя не убьет джедай, </p>
    <p>а то нам даже пришлось нанимать веб-разработчика чтобы вербовать вас быстрее)</p>
    <a href="{% url 'core:main' %}"><button>На главную</button></a>
{% endblock %}

Death_star/templates/core/create_recruit.html
{% extends 'core/wrapper.html' %}

{% block title %}Назовись, рекрут{% endblock %}
{% block content %}
    <form method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Далее">
    </form>
{% endblock %}

Death_star/templates/core/index.html
{% extends 'core/wrapper.html' %}

{% block header %}
    <h2>Тренировочный лагерь руки тьмы</h2>
{% endblock %}

{% block content %}
    <a href="{% url 'core:all_siths' %}"><button>Для ситхов</button></a>
    <a href="{% url 'core:create_rec' %}"><button>Для рекрутов</button></a>
{% endblock %}

Death_star/templates/core/notify.html
{% extends 'core/wrapper.html' %}

{% block title %}Оповещение{% endblock %}

{% block header %}<h2 style="color: red">{{ message }}</h2>{% endblock %}

{% block content %}
    <h3>{{ error }}</h3>
    <a href="{% url 'core:all_recruits' %}"><button>Назад</button></a>
    <a href="{% url 'core:main' %}"><button>На главную</button></a>
{% endblock %}

Death_star/templates/core/questions.html
{% extends 'core/wrapper.html' %}

{% block title %}Тест{% endblock %}
{% block content %}
    <form method="post">
            {% csrf_token %}
           <h3>Questions</h3>
            {% for question in question_list %}
                <p> Вопрос номер: {{ question.id }}</p>
                <p>{{ question.description }}</p>
                <label for="{{ question.id }}">Ответ:</label>
                <input id="{{ question.id }}" name="answer-{{ question.id }}" required>
            {% endfor %}
            <input type="submit" value="Готово">
    </form>
{% endblock %}

Death_star/templates/core/recruit_detail.html
{% extends 'core/wrapper.html' %}

{% block title %}Оповещение{% endblock %}

{% block header %}
    <h2>Результаты теста рекрута: {{ recruit.name }}</h2>
    <h3>Возраст: {{ recruit.age }}</h3>
    <h3>Почта: {{ recruit.email }}</h3>
    <h3>Родная планета: {{ recruit.planet.name }}</h3>
    <a href="{% url 'core:all_recruits' %}"><button>Назад</button></a>
{% endblock %}

{% block content %}
    {% for answer in recruit_answers %}
        <p>На вопрос: {{ answer.task.description }}</p>
        <p>Рекрут дал ответ: {{ answer.choice_text }}</p>
    {% endfor %}
{% endblock %}

Death_star/templates/core/recruits_list.html
{% extends 'core/wrapper.html' %}

{% block title %}Наши рекруты{% endblock %}

{% block header %}
    <h2>Рекруты, прошедшие тест Руки Тени</h2>
    <a href="{% url 'core:all_siths_shortcut' %}"><button>Ситхи с более чем одним учеником</button></a>
{% endblock %}

{% block content %}
    {{ error }}
    <form method="post">
        {% csrf_token %}
        {% for recruit in rec_list %}
            {% if recruit.is_complete_test and not recruit.is_shadow_hand %}
                <p><p>Имя рекрута: {{ recruit.name }}</p>
                <p>Родная планета: {{ recruit.planet.name }}</p>
                <input type="checkbox" id="recruit-{{ recruit.id }}" name="recruit-id" value="{{ recruit.id }}">
                <a href="{% url 'core:rec_detail' recruit.id %}">Посмотреть результаты теста</a></p>
            {% endif %}
        {% endfor %}
        <input type="submit" value="Выбрать">
    </form>
{% endblock %}

Death_star/templates/core/siths_list.html
{% extends 'core/wrapper.html' %}

{% block title %}Добро пожаловать{% endblock %}

{% block header %}
    <h2>Склоняюсь перед вашей мудростью, владыка</h2>
{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {% for sith in siths_list %}
        <p><label for="sith-id">Количество рук тьмы: {{ sith.padavans.count }}</label>
        <input type="submit" name="sith-id" value="{{ sith.name }}"></p>
    {% endfor %}
    </form>
{% endblock %}

Death_star/templates/core/siths_list_shortcut.html
{% extends 'core/wrapper.html' %}

{% block title %}Почетная доска{% endblock %}

{% block header %}
    <h2>Ситхи с более чем одним учеником</h2>
    <a href="{% url 'core:all_recruits' %}"><button>Назад</button></a>
{% endblock %}

{% block content %}
    {% for sith in siths_list %}
        {% if sith.padavans.count > 1 %}
            <p>Владыка {{ sith.name }} c {{ sith.planet.name }}</p>
        {% endif %}
    {% endfor %}
{% endblock %}

Death_star/templates/core/wrapper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block extra_css %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block extra_js %}
    {% endblock %}
</body>
</html>